### ISSUE TITLE
Enom uid and password - is this same as login?

### ISSUE THREAD

**Issue by sei-vsarvepalli** [linux4me/enom_dnssec_tool#1]
I cannot find clear documentation on the uid and password for the reseller account setup. It looks to me like the API Key is the password? But is there a distinct uid that is different from the username used to login at Enom.

I have contacted their support but never got anything back. If you have any insight I will appreciate it very much!

**Comment by linux4me** [comment]
The uid and the password are your Enom reseller account's user ID and password.

**Comment by sei-vsarvepalli** [comment]
Thanks. Looks like you can use the API_Token you create as the password which is preferred. I think the resellertest.enom.com and reseller.enom.com have different username/passwords.  That was more my confusion when I try to update your main.js to use test domain.

Thanks
Vijay

**Comment by linux4me** [comment]
> Looks like you can use the API_Token you create as the password

Good to know. That would be better in terms of security. Thanks for sharing.

**Comment by linux4me** [comment]
I didn't find the resellertest to be helpful. 

To test, you can use a live domain and the command "Get DNSSEC", which won't alter anything, but should confirm that you can connect successfully.
